sudo: required
services:
  - docker

before_install:
  - docker build -t hare1310/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hare1310/react-test npm test -- --coverage
  
after_success:
  - docker build -t hare1310/multi-client ./client
  - docker build -t hare1310/multi-nginx ./nginx
  - docker build -t hare1310/multi-server ./server
  - docker build -t hare1310/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hare1310/multi-client
  - docker push hare1310/multi-nginx
  - docker push hare1310/multi-server
  - docker push hare1310/multi-worker